import type { GraphEntityKind, GraphRelationshipKind } from '@/lib/graph/graphTypes'

/** Human labels for entity kinds (filters, legend, inspector). */
export const ENTITY_LABEL: Record<GraphEntityKind, string> = {
  project: 'Project',
  board: 'Board',
  section: 'Section',
  note: 'Note',
  document: 'Document',
  spreadsheet: 'Spreadsheet',
  presentation: 'Presentation',
  code: 'Code',
  asset: 'Asset',
  pdf: 'PDF',
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
  'model-3d': '3D model',
  'web-embed': 'Web embed',
  comment: 'Comment',
  version: 'Version',
  user: 'Person',
  tag: 'Tag',
  'github-file': 'GitHub',
  'external-file': 'External file',
  'plugin-entity': 'Plugin entity',
}

/** Human labels for relationship kinds. */
export const RELATIONSHIP_LABEL: Record<GraphRelationshipKind, string> = {
  references: 'References',
  backlink: 'Backlink',
  contains: 'Contains',
  'belongs-to': 'Belongs to',
  'embedded-in': 'Embedded in',
  'displayed-on': 'Displayed on',
  'source-of': 'Source of',
  'imported-from': 'Imported from',
  'linked-to': 'Linked on board',
  'depends-on': 'Depends on',
  'parent-of': 'Parent of',
  'child-of': 'Child of',
  'tagged-with': 'Tagged with',
  mentions: 'Mentions',
  'created-by': 'Created by',
  'edited-by': 'Edited by',
  'commented-on': 'Commented on',
  'version-of': 'Version of',
  'github-source': 'GitHub source',
  'external-source': 'External source',
  'generated-by': 'Generated by',
  'suggested-related': 'AI: suggested related',
  'plugin-defined': 'Plugin relationship',
}

/** Node kinds offered in the filter panel, grouped for readability. */
export const FILTERABLE_ENTITY_KINDS: { group: string; kinds: GraphEntityKind[] }[] = [
  {
    group: 'Knowledge',
    kinds: ['note', 'document', 'spreadsheet', 'presentation', 'code'],
  },
  { group: 'Structure', kinds: ['board', 'project', 'tag'] },
  {
    group: 'Assets',
    kinds: ['asset', 'pdf', 'image', 'video', 'audio', 'model-3d', 'web-embed'],
  },
  { group: 'External', kinds: ['github-file'] },
]

/** Relationship kinds offered in the filter panel. */
export const FILTERABLE_RELATIONSHIP_KINDS: GraphRelationshipKind[] = [
  'references',
  'contains',
  'linked-to',
  'imported-from',
  'depends-on',
  'tagged-with',
  'github-source',
  'displayed-on',
]
